# Имя workflow, отображаемое в интерфейсе GitHub Actions
name: Deploy Infrastructure

# Триггеры запуска workflow
on:
  # Запуск при пуше в ветку main (после мержа PR)
  push:
    branches: [ main ]
    paths:
      - 'infrastructure/**'  # Только при изменении файлов в папке infrastructure/
  # Запуск при создании или обновлении Pull Request (для проверки плана)
  pull_request:
    branches: [ main ]
    paths:
      - 'infrastructure/**'
  # Возможность ручного запуска из интерфейса GitHub
  workflow_dispatch:

# Определение задач (jobs)
jobs:
  # Задача для проверки плана в Pull Request (без применения изменений)
  terraform-plan:
    name: Terraform Plan (PR)
    runs-on: ubuntu-latest
    # Запускается только для событий pull_request
    if: github.event_name == 'pull_request'
    steps:
      # Клонирование репозитория
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Terraform plugins
        uses: actions/cache@v4
        with:
          path: infrastructure/.terraform
          key: ${{ runner.os }}-terraform-${{ hashFiles('infrastructure/**/*.tf') }}
          restore-keys: |
            ${{ runner.os }}-terraform-

      # Установка Terraform указанной версии
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.2

      # Инициализация Terraform с передачей параметров бэкенда через -backend-config
      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="access_key=$TF_VAR_access_key" \
            -backend-config="secret_key=$TF_VAR_secret_key" \
        working-directory: ./infrastructure
        env:
          TF_VAR_access_key: ${{ secrets.YC_ACCESS_KEY }}
          TF_VAR_secret_key: ${{ secrets.YC_SECRET_KEY }}
          TF_VAR_service_account_key: ${{ secrets.YC_SERVICE_ACCOUNT_KEY }}
          TF_VAR_cloud_id: ${{secrets.YC_CLOUD_ID}}
          TF_VAR_folder_id: ${{ secrets.YC_FOLDER_ID }}

      # План изменений (без применения)
      - name: Terraform Plan
        run: terraform plan
        working-directory: ./infrastructure
        env:
          TF_VAR_access_key: ${{ secrets.YC_ACCESS_KEY }}
          TF_VAR_secret_key: ${{ secrets.YC_SECRET_KEY }}
          TF_VAR_service_account_key: ${{ secrets.YC_SERVICE_ACCOUNT_KEY }}
          TF_VAR_cloud_id: ${{secrets.YC_CLOUD_ID}}
          TF_VAR_folder_id: ${{ secrets.YC_FOLDER_ID }}

  # Задача для применения изменений в ветке main
  terraform-apply:
    name: Terraform Apply (main)
    runs-on: ubuntu-latest
    # Запускается только при пуше в main
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Terraform plugins
        uses: actions/cache@v4
        with:
          path: infrastructure/.terraform
          key: ${{ runner.os }}-terraform-${{ hashFiles('infrastructure/**/*.tf') }}
          restore-keys: |
            ${{ runner.os }}-terraform-
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.2

      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="access_key=$TF_VAR_access_key" \
            -backend-config="secret_key=$TF_VAR_secret_key" \
        working-directory: ./infrastructure
        env:
          TF_VAR_access_key: ${{ secrets.YC_ACCESS_KEY }}
          TF_VAR_secret_key: ${{ secrets.YC_SECRET_KEY }}
          TF_VAR_service_account_key: ${{ secrets.YC_SERVICE_ACCOUNT_KEY }}
          TF_VAR_cloud_id: ${{secrets.YC_CLOUD_ID}}
          TF_VAR_folder_id: ${{ secrets.YC_FOLDER_ID }}

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./infrastructure
        env:
          TF_VAR_access_key: ${{ secrets.YC_ACCESS_KEY }}
          TF_VAR_secret_key: ${{ secrets.YC_SECRET_KEY }}
          TF_VAR_service_account_key: ${{ secrets.YC_SERVICE_ACCOUNT_KEY }}
          TF_VAR_cloud_id: ${{secrets.YC_CLOUD_ID}}
          TF_VAR_folder_id: ${{ secrets.YC_FOLDER_ID }}